name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        boot: '2.8.3'
    - run: boot build
